### ISSUE TITLE
fails to build on ubuntu 17.04

### ISSUE THREAD

**Issue by rbuckland** [six-ddc/httpflow#2]
```
~/projects/github.com/six-ddc/httpflow$ sudo apt-get install libpcap-dev zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpcap-dev is already the newest version (1.8.1-3ubuntu1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 34 not to upgrade.
~/projects/github.com/six-ddc/httpflow$ make && make install
g++ -lz -lpcap -lpcre http_flow.o http_parser.o custom_parser.o util.o data_link.o -o httpflow
http_flow.o: In function `print_usage()':
http_flow.cpp:(.text+0xd2): undefined reference to `pcap_lib_version'
http_flow.o: In function `init_capture_config(int, char**, capture_config*, char*)':
http_flow.cpp:(.text+0x4a4): undefined reference to `pcre_compile'
http_flow.cpp:(.text+0x4be): undefined reference to `pcre_study'
http_flow.cpp:(.text+0x56c): undefined reference to `pcap_lookupdev'
http_flow.o: In function `main':
http_flow.cpp:(.text.startup+0xa9): undefined reference to `pcap_lookupnet'
http_flow.cpp:(.text.startup+0xc6): undefined reference to `pcap_open_live'
http_flow.cpp:(.text.startup+0xda): undefined reference to `pcap_datalink'
http_flow.cpp:(.text.startup+0xf5): undefined reference to `pcap_compile'
http_flow.cpp:(.text.startup+0x109): undefined reference to `pcap_setfilter'
http_flow.cpp:(.text.startup+0x11a): undefined reference to `pcap_freecode'
http_flow.cpp:(.text.startup+0x122): undefined reference to `pcap_datalink'
http_flow.cpp:(.text.startup+0x1f2): undefined reference to `pcap_loop'
http_flow.cpp:(.text.startup+0x246): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x252): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x28c): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x2db): undefined reference to `pcap_open_offline'
http_flow.cpp:(.text.startup+0x309): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x37b): undefined reference to `pcap_geterr'
custom_parser.o: In function `custom_parser::filter_url(real_pcre const*, pcre_extra const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
custom_parser.cpp:(.text+0xb1f): undefined reference to `pcre_exec'
util.o: In function `gzip_decompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
util.cpp:(.text+0x588): undefined reference to `inflateInit2_'
util.cpp:(.text+0x5d8): undefined reference to `inflate'
util.cpp:(.text+0x60f): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by cisiqo** [comment]
g++ -O2 -I/usr/local/include -c http_flow.cpp -o http_flow.o
g++ -O2 -I/usr/local/include -c http_parser.cpp -o http_parser.o
g++ -O2 -I/usr/local/include -c custom_parser.cpp -o custom_parser.o
g++ -O2 -I/usr/local/include -c util.cpp -o util.o
g++ -O2 -I/usr/local/include -c data_link.cpp -o data_link.o
g++ -lz -lpcap -lpcre http_flow.o http_parser.o custom_parser.o util.o data_link.o -o httpflow
http_flow.o: In function `print_usage()':
http_flow.cpp:(.text+0x2): undefined reference to `pcap_lib_version'
http_flow.o: In function `init_capture_config(int, char**, capture_config*, char*)':
http_flow.cpp:(.text+0x284): undefined reference to `pcre_compile'
http_flow.cpp:(.text+0x2a0): undefined reference to `pcre_study'
http_flow.cpp:(.text+0x332): undefined reference to `pcap_lookupdev'
http_flow.o: In function `main':
http_flow.cpp:(.text.startup+0x95): undefined reference to `pcap_lookupnet'
http_flow.cpp:(.text.startup+0xb4): undefined reference to `pcap_open_live'
http_flow.cpp:(.text.startup+0xc8): undefined reference to `pcap_datalink'
http_flow.cpp:(.text.startup+0xe0): undefined reference to `pcap_compile'
http_flow.cpp:(.text.startup+0xf6): undefined reference to `pcap_setfilter'
http_flow.cpp:(.text.startup+0x109): undefined reference to `pcap_freecode'
http_flow.cpp:(.text.startup+0x111): undefined reference to `pcap_datalink'
http_flow.cpp:(.text.startup+0x1bc): undefined reference to `pcap_loop'
http_flow.cpp:(.text.startup+0x205): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x211): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x23e): undefined reference to `pcap_close'
http_flow.cpp:(.text.startup+0x28c): undefined reference to `pcap_open_offline'
http_flow.cpp:(.text.startup+0x2b1): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x2f9): undefined reference to `pcap_geterr'
http_flow.cpp:(.text.startup+0x326): undefined reference to `pcap_close'
custom_parser.o: In function `custom_parser::filter_url(real_pcre const*, pcre_extra const*, std::string const&)':
custom_parser.cpp:(.text+0x749): undefined reference to `pcre_exec'
util.o: In function `gzip_decompress(std::string&, std::string&)':
util.cpp:(.text+0x164): undefined reference to `inflateInit2_'
util.cpp:(.text+0x1b7): undefined reference to `inflate'
util.cpp:(.text+0x1e5): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

Ubuntu 14.04.5 has the same .
